blank_issues_enabled: true
contact_links:
  - name: ğŸ¤· Installation Help
    url: https://discord.gg/tTvd94mdbn
    about: Please visit our Discord for help with your installation.
  - name: â“ General Question
    url: https://discord.gg/tTvd94mdbn
    about: Please visit our Discord for general questions about the LAN-Party Manager.